title: Isaac Buabeng
logo: https://github.com/ikb001/ikb.github.io/blob/main/assets/LinkedIn-0055.jpg
#description: Computational Ecology|Biodiversity Data Science
#show_downloads: true
theme: jekyll-theme-minimal
